name: Editor
version: 0.1.0.0
synopsis: a text editor
description: ""
category: Development
author: Armeddon
maintainer: artkul204@gmail.com
license: BSD-3-Clause
license-file: LICENSE
extra-doc-files:
  - CHANGELOG.md
build-type: Simple

ghc-options: -Wall -threaded

executables:
  Editor:
    main: Main.hs
    source-dirs: app
    dependencies:
      - base ^>= 4.18.3.0
      - text
      - text-zipper
      - containers
      - safe
      - brick ^>= 2.8.3
      - vty ^>= 6.4
      - lens
    language: Haskell2010

